### ISSUE TITLE
Noto equivalent?

### ISSUE THREAD

**Issue by polarathene** [adobe-fonts/source-han-mono#1]
Adobe's "Source" and Google's "Noto" branded fonts afaik [are stated to be the same fonts just with different branding](https://github.com/adobe-fonts/source-han-sans/issues/122). Yet I've come across individual repos for each, it's not clear if there's been some divergence / tweaks to either that differentiates them since.

I know that "Noto Mono" got deprecated in favor of "Noto Sans Mono". And that there are CJK equivalents such as "Noto Sans CJK JP" for Japanese support. Meanwhile on Adobe's end there was/is "Source Han Code JP", ~~there does not seem to be any monospace equivalent that these Noto versions were derived from?~~(**EDIT:** [There is](https://github.com/adobe-fonts/source-han-sans/issues/123), they're just called HW for Half-Width instead, the repo README just doesn't clarify this distinction to a user) [They've been around for a while(2015)](https://github.com/googlefonts/noto-cjk/commits/master/NotoSansMonoCJKjp-Regular.otf) and seem to be described as:

> *Note: New in release 1.002 were 'Monospace' versions. These provide half-width
instead of proportional widths for ASCII (U+0020 to U+007E) and the following
characters: U+00A0, U+00A5, U+2011, and U+20A9. These come in two weights
(Regular and Bold) for each of the five languages. These fonts have 'Mono' in
the family name, e.g. 'Noto Sans Mono CJK {HK, JP, KR, SC, TC}'.* - [Noto CJK repo README](https://github.com/googlefonts/noto-cjk)

Then this year, you have released "Source Han Mono"(which is very welcome, thank you :smiley: ). **Is this a distinction Adobe will have, or will Google's Noto be rebranding or replacing their existing half-width sans mono fonts based on this project?**

---

I have also come across [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) which combines Iosevka with Source Han Sans for a programming font. They provide both japanese and chinese support(but not korean for some reason). Now that Source Han Mono is available, they'd presumably benefit from sourcing this project instead for composing their font?

**Comment by kenlunde** [comment]
@polarathene _Source Han Mono_ was a personal project of mine, and because there was no contract with Google to produce a Google-branded version, an equivalent _Noto CJK_ was not produced. I am no longer able to manage this project, so please close this issue yourself.

**Comment by polarathene** [comment]
Oh, did Google have a contract with Adobe for adopting the fonts for their Noto brand? Is that required for them to adopt Source Han Mono under that umbrella too, or does the license allow for it regardless?

Is this project likely to see any future work if required? Who is the new maintainer(if there is one)? Thank you for all your work and contributions :)

**Comment by kenlunde** [comment]
@polarathene A non-trivial amount of work is necessary to produce a Google-branded version of _Source Han Mono_, which is precisely why a Google-branded version never materialized. I consider the _Noto CJK_ fonts to be clones of the equivalent _Source Han_ fonts, and not the other way around. Adobe holds the copyright to the _Source Han_ fonts, which is also telling.
